# Generated by Django 3.2.4 on 2021-07-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('comentario', models.TextField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
